### ISSUE TITLE
Authenticate when jitsi is hosted in an isolated network

### ISSUE THREAD

**Issue by mikaeldusenne** [nordeck/jitsi-keycloak-adapter#15]
**Is your feature request related to a problem? Please describe.**

Jitsi and Keycloak both sit behind a Nginx reverse proxy.
Jitsi and Keycloak cannot resolve public addresses, and the user's browser cannot resolve addresses from the Jitsi / Keycloak private network.

The environment variable `KEYCLOAK_ORIGIN` is supposed to be accessible for the container (and exchange the auth code for an access token), but we therefore cannot use it to redirect the user (which is needed for credentials input).

**Describe the solution you'd like**

I believe that allowing for two different endpoints, a public one and a private one, would allow to solve this issue. The default could be to set the private endpoint to be the same as the public one, so that backward compability will not be broken.

**Describe alternatives you've considered**

Changing my network's structure is not planned, and I believe this is a common case anyway, so a fix could be helpful :)

**Comment by emrahcom** [comment]
Hi @mikaeldusenne, thank you very much for the report and pull-request.

Although the pull-request is OK for me, I think that using `KEYCLOAK_AUTHORIZATION_ENDPOINT` and `KEYCLOAK_ORIGIN` to point the same service is a bit  confusing. Therefore I prepared a similar patch by using a different term.

Does this fix the issue on your side?

**Comment by mikaeldusenne** [comment]
Hi @emrahcom,

I do agree that the use of these two variables might be a bit confusing, maybe in part because of their naming.
I am not a master of OIDC, and I tried to map the [OIDC reference](https://openid.net/specs/openid-connect-core-1_0.html#AuthorizationEndpoint).
Technically I suppose KEYCLOAK_ORIGIN coule be named "[Token Endpoint](https://openid.net/specs/openid-connect-core-1_0.html#TokenEndpoint)", but then this would become a breaking change, and I am not sure about the best design choice :).

The issue is indeed fixed with my pull request (Thank you for giving me the opportunity to track the issue !) and I can authenticate jitsy with keycloak even when jitsi is running on an isolated network.

Please let me know if I can provide any further information / testing !

**Comment by emrahcom** [comment]
Hi @mikaeldusenne,

I use `KEYCLOAK_ORIGIN` to specify the base address of the endpoint. Actually it is not the endpoint, it is [the origin](https://developer.mozilla.org/en-US/docs/Web/API/URL/origin) of the endpoint. The endpoint is generated lately in [the code](https://github.com/nordeck/jitsi-keycloak-adapter/blob/main/adapter.ts#L110-L111).

Thank you again to report this issue and pull-request.
