### ISSUE TITLE
jitsi-keycloak-adapter does not scope issued JWTs

### ISSUE THREAD

**Issue by micolous** [nordeck/jitsi-keycloak-adapter#21]
[Jitsi Meet](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md#token-structure) uses two non-standard claims to scope a JWT:

* `sub`: which contains either a tenant identifier, domain, or `*` (allow all)
* `room`: which contains a room name or `*` (allow all)

`jitsi-keycloak-adapter` sets both of these to `*`:

https://github.com/nordeck/jitsi-keycloak-adapter/blob/037799fd8322270b2d1cd6a0a6673ee3d3c62ac1/adapter.ts#L82-L83

There does not appear to be any way to limit the scope of the issued tokens, so they will be valid for any Jitsi instance which accepts JWTs from the `jitsi-keycloak-adapter` instance.

**Comment by emrahcom** [comment]
Hi @micolous, thank you for the bug report.

I think it is fixed now: https://github.com/nordeck/jitsi-keycloak-adapter/commit/726a579c3b210e4b5bac9d79856aefdaf2c92368
