### ISSUE TITLE
Configuration for name mapping

### ISSUE THREAD

**Issue by mandree95** [nordeck/jitsi-keycloak-adapter#3]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
We would like to have the ability to configure the mapping for the display name.

For example, as a concrete example, Keycloak's fullname mapper could be used to map the full display name as a token claim name in the access token and pass it to Jitsi. Currently the Jitsi mapping is hardcoded to use `preferred_username`. We would like to be able to change that to for ex. `userInfo.name`.

It would also be good if a suffix could be configured which, if set, would be appended to the name as a suffix.

**Describe alternatives you've considered**
We've also considered to implement this directly into Keycloak. But this does not look like a good solution.

**Additional context**
The current name mapping can be found at the following location: https://github.com/nordeck/jitsi-keycloak-adapter/blob/main/adapter.ts#L78

**Comment by emrahcom** [comment]
Hi @mandree95,

The context logic comes from [context.ts](https://github.com/nordeck/jitsi-keycloak-adapter/blob/main/context.ts) now. It is not a declarative way to do it but more flexible for most cases.

You may update this file for your setup.
